<?php

namespace Alyya\JobeetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlyyaJobeetBundle/Repository/JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlyyaJobeetBundle/Repository/JobRepository extends EntityRepository
{
}
