alyya_jobeet_alyya_job:
    resource: "@AlyyaJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

alyya_jobeet_homepage:
    path:     /
    defaults: { _controller: AlyyaJobeetBundle:Job:index }

alyya_category_show :
    path:     /category/{slug}/{page}
    defaults: { _controller: AlyyaJobeetBundle:Category:show , page: 1 }
    requirements:
      page: \d+
