alyya_job_index:
    path:     /
    defaults: { _controller: "AlyyaJobeetBundle:Job:index" }
    methods:  GET

alyya_job_show:
    path:     /{company}/{location}/{id}/{position}
    defaults: { _controller: "AlyyaJobeetBundle:Job:show" }
    methods:  GET
    requirements:
      id: \d+
alyya_job_preview:
    path:     /{company}/{location}/{token}/{position}
    defaults: { _controller: "AlyyaJobeetBundle:Job:preview" }
    methods:  GET
    requirements:
        token: \w+

alyya_job_publish:
  path: /{token}/publish
  defaults: {_controller: "AlyyaJobeetBundle:Job:publish"}
  methods: POST
  requirements:
    token: \w+

alyya_job_extend:
    path: /{token}/extend
    defaults: {_controller: "AlyyaJobeetBundle:Job:extend"}
    requirements:
      token: \w+

alyya_job_new:
    path:     /new
    defaults: { _controller: "AlyyaJobeetBundle:Job:new" }
    methods:  [GET, POST]

alyya_job_edit:
    path:     /{token}/edit
    defaults: { _controller: "AlyyaJobeetBundle:Job:edit" }
    methods:  [GET, POST]

alyya_job_delete:
    path:     /{token}/delete
    defaults: { _controller: "AlyyaJobeetBundle:Job:delete" }
    methods:  DELETE
